"use strict";
exports.__esModule = true;
var stats_tracker_1 = require("./stats-tracker");
var test_1 = require("./test");
var game_character_factory_1 = require("./game-character-factory");
var tracker = stats_tracker_1.StatsTracker.instance;
tracker.widgetViews = 90;
tracker.buttonClicks = 64;
tracker.facebookShares = 20;
tracker.twitterShares = 30;
console.log("Widget view: " + tracker.widgetViews);
console.log("Button clicks: " + tracker.buttonClicks);
console.log("Facebook shares: " + tracker.facebookShares);
console.log("Twitter shares: " + tracker.twitterShares);
tracker.widgetViews++;
tracker.twitterShares;
test_1.test();
var warrior = game_character_factory_1.GameCharacterFactory.getWarrior(6);
var mage = game_character_factory_1.GameCharacterFactory.getMage(12);
console.log("Warrior at");
